print(3 + 4)   # addition(+)
print(3 - 4)   # subtraction(-)
print(3 * 4)   # multiplication(*)
print(3 / 4)   # division(/)
print(3 ** 4)  # exponential(**)
print(3 % 4)   # modulus(%)
print(3 // 4)  # Floor division operator(//)

print("Jesus Alejandro")
print("Villaobos")
print("Mexico")
print("I am enjoying 30 days of python")

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh','Python','Finland']))
print(type('Jesus Alejandro'))
print(type('Villaobos'))
print(type('Mexico'))
print(type('I am enjoying 30 days of python'))